# Generated by Django 5.1.1 on 2024-10-03 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField(help_text='Tempo em minutos')),
                ('categoria', models.CharField(choices=[('E', 'Entrada'), ('P', 'Prato Principal'), ('S', 'Sobremesa'), ('B', 'Bebida')], max_length=1)),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
