# Generated by Django 5.1.2 on 2024-10-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_profile_codigo_verificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
